defaults:
  - _self_
  - mode: eval
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

model_filename: "model_100_4"
model_dir_name: "model"
control_frequency: 55 #55 Hz

serial:
  in_buffer_size: 4
  out_buffer_size: 2
  baudrate: 31250
  port: 'COM3'
  timeout: 1
  max_startup_t: 5
  auth_str: "<ready>"
  sleep_t: 0.01

encoder:
  reset_encoder_t: 20
  encoder_reset_thresh: 900

action_space:
  actual_half_range: 20000
  half_range: 2
#  interval: 100

# element position: theta, angular_vel, motor_pos, motor_vel
observation_space:
  lower_bound: [-1, -1, -10, -3, -4]
  upper_bound: [1, 1, 10, 3, 4]

# motor half_range can record up to 300, but is bounded to 200
calc:
  vel_modifier: 0.2
  motor_vel_modifier: 0.25
  motor_half_range: 300
  motor_half_limit: 200
  motor_norm_half_range: 3
  # accel_modifier: 0.1

reward:
  vel_weight: 0.1
  motor_pos_weight: 0.1
  motor_vel_weight: 0.02
  control_weight: 0.5
  reward_offset: 15
  # accel_weight: 0.001
  # old control: 0.1, old motor_pos_weight: 0.05, vel_weight: 0.05

hydra:
  output_subdir: null
  run:
    dir: .
