defaults:
  - _self_
  - mode: train
  - model: SAC
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

model_filename: "model_100_5"
model_dir_name: "model"
control_frequency: 55 #55 Hz

# only relevant for train_model_with_tensorboard
logging:
  enabled: False
  dir_name: "logs" # for logging training progress data
  run_name: "model_100_4"

serial:
  in_buffer_size: 4
  out_buffer_size: 2
  baudrate: 31250
  port: 'COM3'
  timeout: 1
  max_startup_t: 5
  auth_str: "<ready>"
  sleep_t: 0.01

encoder:
  reset_encoder_t: 20
  encoder_reset_thresh: 600 # number of rotations in encoder before resetting encoder
  # if rotations in one direction is too large and not reset, the encoder data will overflow.

action_space:
  actual_half_range: 20000
  half_range: 2

# element position: cos theta, sin theta, angular_vel, motor_pos, motor_vel
observation_space:
  lower_bound: [-1, -1, -10, -3, -4]
  upper_bound: [1, 1, 10, 3, 4]

# motor half_range can record up to 300, but is bounded to 200
calc:
  vel_modifier: 0.2
  motor_vel_modifier: 0.25
  motor_half_range: 300
  motor_half_limit: 200
  motor_norm_half_range: 3

reward:
  vel_weight: 0.1
  motor_pos_weight: 0.4
  motor_vel_weight: 0.02
  control_weight: 0.2
  reward_offset: 15
  # old control: 0.1, old motor_pos_weight: 0.05, vel_weight: 0.05

hydra:
  output_subdir: null
  run:
    dir: .
