defaults:
  - _self_
  - mode: train
  - override hydra/hydra_logging: disabled
  - override hydra/hydra_logging: disabled

model_filename: "model_latest.pkl"
model_dir_name: "model"

episode:
  episode_length: 500
  episodes: 500

serial:
  in_buffer_size: 4
  out_buffer_size: 2
  baudrate: 9600
  port: 'COM3'
  timeout: 1
  max_startup_t: 5
  auth_str: "<ready>"
  sleep_t: 0.01

action_space:
  half_range: 2
  actual_half_range: 20000
#  interval: 100

# element position: theta, angular_vel, motor_pos, motor_vel
observation_space:
  lower_bound: [-3.2, -15, -3, -4]
  upper_bound: [3.2, 15, 3, 4]

# motor half_range can record up to 300, but is bounded to 200
calc:
  vel_modifier: 0.1
  motor_vel_modifier: 0.25
  motor_half_range: 300
  motor_half_limit: 200
  motor_norm_half_range: 3
  # accel_modifier: 0.1


reward:
  vel_weight: 0.1
  motor_pos_weight: 0.1
  motor_vel_weight: 0.02
  control_weight: 0.03
  terminal_penalty: 15
  # accel_weight: 0.001