defaults:
  - _self_
  - mode: train
  - override hydra/hydra_logging: disabled
  - override hydra/hydra_logging: disabled

model_filename: "model_latest.pkl"
model_dir_name: "model"

serial:
  baudrate: 9600
  port: 'COM3'
  timeout: 1
  max_startup_t: 5
  auth_str: "<ready>"
  sleep_t: 0.01

action_space:
  interval: 100
  half_range: 20000

# element position: x=cos(theta), y=sin(theta), angular vel
observation_space:
  lower_bound: [-1, -1, -15]
  upper_bound: [1, 1, 15]

calc:
  vel_modifier: 0.5
  accel_modifier: 0.1

reward:
  vel_weight: 0.1
  accel_weight: 0.001