defaults:
  - _self_
  - model: SAC

name: "train"

from_scratch: False
overwrite: False
new_model_filename: "model_100" # if not overwrite, save new model as this

episode_length: 500
total_timesteps: 1e5