name: "train"

from_scratch: False # note that modeL_filename in config.yaml is irrelevant when this is True
overwrite: False
new_model_filename: "model_100_5" # if not overwrite, save new model as this

episode_length: 500
total_timesteps: 1e4